/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajasacr;

import java.beans.PropertyVetoException;

/**
 *
 * @author desarrollo01
 */
public class frmMenu extends javax.swing.JFrame {

   /**
    * Creates new form frmMenu
    */
   public frmMenu() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      PanelPrincipal = new javax.swing.JDesktopPane();
      jMenuBar1 = new javax.swing.JMenuBar();
      jmnOperaciones = new javax.swing.JMenu();
      jmiApertura = new javax.swing.JMenuItem();
      jmiRegMov = new javax.swing.JMenuItem();
      jmnMantenimiento = new javax.swing.JMenu();
      jmiRegCaja = new javax.swing.JMenuItem();
      jmiRegCajero = new javax.swing.JMenuItem();
      jmiTegTipPago = new javax.swing.JMenuItem();
      jmnReporte = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
      PanelPrincipal.setLayout(PanelPrincipalLayout);
      PanelPrincipalLayout.setHorizontalGroup(
         PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 901, Short.MAX_VALUE)
      );
      PanelPrincipalLayout.setVerticalGroup(
         PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 432, Short.MAX_VALUE)
      );

      jmnOperaciones.setText("Operaciones");

      jmiApertura.setText("Apertura Caja");
      jmiApertura.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiAperturaActionPerformed(evt);
         }
      });
      jmnOperaciones.add(jmiApertura);

      jmiRegMov.setText("Registro Movimientos");
      jmiRegMov.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiRegMovActionPerformed(evt);
         }
      });
      jmnOperaciones.add(jmiRegMov);

      jMenuBar1.add(jmnOperaciones);

      jmnMantenimiento.setText("Mantenimiento");

      jmiRegCaja.setText("Registro Caja");
      jmiRegCaja.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiRegCajaActionPerformed(evt);
         }
      });
      jmnMantenimiento.add(jmiRegCaja);

      jmiRegCajero.setText("Registro Cajero");
      jmiRegCajero.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiRegCajeroActionPerformed(evt);
         }
      });
      jmnMantenimiento.add(jmiRegCajero);

      jmiTegTipPago.setText("Registro Tipo Pago");
      jmiTegTipPago.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiTegTipPagoActionPerformed(evt);
         }
      });
      jmnMantenimiento.add(jmiTegTipPago);

      jMenuBar1.add(jmnMantenimiento);

      jmnReporte.setText("Reportes");
      jMenuBar1.add(jmnReporte);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 29, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 95, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jmiRegCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegCajaActionPerformed
      // TODO add your handling code here:
      
      frmRegistroCaja frm = new frmRegistroCaja(); 
      frm.setVisible(true);
      PanelPrincipal.add(frm);
      try {
         frm.setSelected(true);
      } catch (java.beans.PropertyVetoException e) {}
            
   }//GEN-LAST:event_jmiRegCajaActionPerformed

   private void jmiRegCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegCajeroActionPerformed
      // TODO add your handling code here:
      frmRegistroCajero frm = new frmRegistroCajero(); 
      frm.setVisible(true);
      PanelPrincipal.add(frm);
      try {
         frm.setSelected(true);
      } catch (java.beans.PropertyVetoException e) {}

   }//GEN-LAST:event_jmiRegCajeroActionPerformed

   private void jmiAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAperturaActionPerformed
      // TODO add your handling code here:
      frmAperturaCaja frm = new frmAperturaCaja(); 
      frm.setVisible(true);
      PanelPrincipal.add(frm);
      try {
         frm.setSelected(true);
      } catch (java.beans.PropertyVetoException e) {}
   }//GEN-LAST:event_jmiAperturaActionPerformed

   private void jmiRegMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegMovActionPerformed
      // TODO add your handling code here:
      frmRegistroMovimi frm = new frmRegistroMovimi(); 
      frm.setVisible(true);
      PanelPrincipal.add(frm);
      try {
         frm.setSelected(true);
      } catch (java.beans.PropertyVetoException e) {}
   }//GEN-LAST:event_jmiRegMovActionPerformed

   private void jmiTegTipPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTegTipPagoActionPerformed
      // TODO add your handling code here:
      frmRegistroTipoPago frm = new frmRegistroTipoPago(); 
      frm.setVisible(true);
      PanelPrincipal.add(frm);
      try {
         frm.setSelected(true);
      } catch (java.beans.PropertyVetoException e) {}
   }//GEN-LAST:event_jmiTegTipPagoActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new frmMenu().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JDesktopPane PanelPrincipal;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jmiApertura;
   private javax.swing.JMenuItem jmiRegCaja;
   private javax.swing.JMenuItem jmiRegCajero;
   private javax.swing.JMenuItem jmiRegMov;
   private javax.swing.JMenuItem jmiTegTipPago;
   private javax.swing.JMenu jmnMantenimiento;
   private javax.swing.JMenu jmnOperaciones;
   private javax.swing.JMenu jmnReporte;
   // End of variables declaration//GEN-END:variables
}
